version: "3.8"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - server
    command: npm run start

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000"
    environment:
      - NODE_ENV=production
    env_file:
      - ./server/.env
    command: npm run start

networks:
  default:
    driver: bridge
