services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /app/node_modules

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    expose:
      - "5000"
    env_file:
      - ./server/.env
    environment:
      - NODE_ENV=production
    volumes:
      - ./server:/app
      - /app/node_modules

networks:
  default:
    driver: bridge
